count colors

diff --git a/main b/main
--- a/main
+++ b/main
@@ -18,7 +18,7 @@ norm_strings="$(normalize-fasta "$1")"
 #echo "==="
 #
 
-lcss="$(echo "$norm_strings" | "$LCSS_BIN" | lcss-to-list --min-common 20)"
+lcss="$(echo "$norm_strings" | "$LCSS_BIN" | lcss-to-list --min-common 10)"
 
 #
 #rep_in_lcss="$(echo "$lcss" | "$LCSS_BIN" | lcss-to-list --min-common 2 | keep-str-in-range --min 3)"
@@ -55,6 +55,10 @@ while read sub; do
 
     idx=$((idx + 1))
 done <<< "$lcss"
+
+if [ "$idx" -gt 255 ]; then
+    echo "error in color-picking" 1>&2
+fi
 
 echo "matching substrings in given sequences:"
 colout "$regexp" "$colors" <<< "$norm_strings"
